/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_siggi_jfsevents_JFSEvents */

#ifndef _Included_io_siggi_jfsevents_JFSEvents
#define _Included_io_siggi_jfsevents_JFSEvents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    allocate
 * Signature: (Lio/siggi/jfsevents/JFSEvents;)J
 */
JNIEXPORT jlong JNICALL Java_io_siggi_jfsevents_JFSEvents_allocate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_siggi_jfsevents_JFSEvents_deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    addPath
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_siggi_jfsevents_JFSEvents_addPath
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    start
 * Signature: (JJJDI)Z
 */
JNIEXPORT jboolean JNICALL Java_io_siggi_jfsevents_JFSEvents_start
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble, jint);

/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    readEvent
 * Signature: (JJ)Lio/siggi/jfsevents/FSEvent;
 */
JNIEXPORT jobject JNICALL Java_io_siggi_jfsevents_JFSEvents_readEvent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    getDeviceId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_siggi_jfsevents_JFSEvents_getDeviceId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_siggi_jfsevents_JFSEvents
 * Method:    getUuidForDevice
 * Signature: (J)Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_io_siggi_jfsevents_JFSEvents_getUuidForDevice
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
